### ISSUE TITLE
How can i use it?

### ISSUE THREAD

**Issue by Radi-go** [jjssoftware/asustor-dropbox#6]
01/12/2020 19:27:06 INFO Process started
01/12/2020 19:27:09 ERROR

01/12/2020 19:27:09 ERROR Caught unhandled exception
Traceback (most recent call last):
  File "/usr/local/AppCentral/community-dropbox-sync/bin/updown.py", line 743, in <module>
    main()
  File "/usr/local/AppCentral/community-dropbox-sync/bin/updown.py", line 100, in main
    download_result = traverse_dropbox_folders(dbx, dropbox_root, local_sync_folder, args)
  File "/usr/local/AppCentral/community-dropbox-sync/bin/updown.py", line 248, in traverse_dropbox_folders
    result = process_metadata_entries(dbx, folder_metadata.entries, path, local_root_dir, args)
  File "/usr/local/AppCentral/community-dropbox-sync/bin/updown.py", line 329, in process_metadata_entries
    if yesno('Download and save %s' % full_dropbox_filename, True, args):
  File "/usr/local/AppCentral/community-dropbox-sync/bin/updown.py", line 566, in yesno
    print(ascii_msg + '? [auto] YES')
TypeError: can't concat str to bytes
01/12/2020 19:27:09 INFO Runtime: 0 days 0 hours 0 mins 3 secs
01/12/2020 19:27:09 INFO process aborted with: Process terminated early due to exception

I use it. Python3 in ASUSTOR

python3 /usr/local/AppCentral/community-dropbox-sync/bin/updown.py --token ****** -y -d / /share/Manager/test/

Dropbox folder name: /
Local directory: /share/Manager/test/
file: b'3D simulator.pdf'
Process terminated early due to exception

How can solve it?

**Comment by bebo-dot-dev** [comment]
> How can solve it?

Install Python v2.7.x 

This code has not been tested with Python v3, if you want it to work with a Python v3 runtime, fork this repo and introduce that change yourself.
